version: "3"

volumes:
  mongodb_volume:

services:
  youtube_statistic:
    build: StatisticManager/
    restart: always
    environment:
      - TZ=Europe/Kiev
      - YOUTUBE_CHANNEL_ID=
      - YOUTUBE_API_KEY=
      - DAYS_STATISTIC_SEND_TIME=09:00
      - WEEK_STATISTIC_SEND_TIME=23:00
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - RESPONSE_DELAY=120
      - NOTIFICATION_SERVICE_URL=
      - NOTIFICATION_SERVICE_CLIENT_ID=
      - NOTIFICATION_SERVICE_MODE=prod
      - STORAGE_SERVICE_IMPL=MongodbService
      - LANGUAGE=UA
      - BASE_REPORT_URL=http://yt.azbest-cloud.ru

  web-service:
    build: WebService/
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Eurape.Kiev
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - STORAGE_SERVICE_IMPL=MongodbService
      - LOG_MODE=dev

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always
